apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tiketi-spring-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_ORG/YOUR_REPO.git
    targetRevision: main
    path: k8s/spring/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: tiketi-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
