apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: urr-spring-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_ORG/YOUR_REPO.git
    targetRevision: main
    path: k8s/spring/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: urr-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
